### ISSUE TITLE
clarify code origin

### ISSUE THREAD

**Issue by faroit** [naetherm/torch_ema#1]
most of the code in this repo looks identical to https://github.com/lucidrains/ema-pytorch 

* I wonder, if this a fork of the repo above?
* if yes it should be clearly labeled as such and the original copyright ownership should still be visible.
* Having two packages on pypi with almost the same name but almost identical code is confusing for users.

@lucidrains

**Comment by naetherm** [comment]
Thanks for the hint @[faroit](https://github.com/faroit), I will take a look into that. 
The project was externalized from a bigger closed-source implementation I am part of. So yes, I will take care about that.

**Comment by naetherm** [comment]
No answer yet but I had time to look into the code. And obviously, with some variable name changes, it's the same code. 
To link that correctly I would need more time but would delete this repository and add the one of lucidrains as submodule.

**Comment by faroit** [comment]
>  To link that correctly I would need more time but would delete this repository and add the one of lucidrains as submodule.

I'm not sure, I understand the issue. You can't just fork a repo and modify the copyright. Either you attribute the original author or delete this repo. As is, this would be referred to as a code plagiarism.

**Comment by naetherm** [comment]
Dear faroit,
I think we're talking past each other. As the code was/is from a closed source project and was not added by me (to this project) I thought is was original work. I also asked the person wo added it whether it would be okay to publish it (without knowing there is a original code-piece) as it looked perfect for making a standalone module and also had the structure for that. 
So yes,  the only valid precedure I see is closing/deleting this repo and using the original piece (which is now done -- and I hope this will reach you as mail notification!).
